title: TaxClock Morocco
description: C'est facil de savoir combien vous payez pour les impots. Mais savez-vous combien de temps vous prend pour payer ces impots? Entrez votre salaire pour savoir comment votre temps est partage entre les impots et votre profits.

url: https://tarikn.github.io/taxclockMorocco1/
enforce_ssl: tarikn.github.io/taxclockMorocco1/

google_analytics: UA-33350783-6
